services:
    erfans_asset.asset_manager:
        class: Erfans\AssetBundle\Asset\AssetManager
        arguments:
          - "%kernel.root_dir%"
          - "@erfans_asset.util.file_system"
          - "@parameter_bag"

    erfans_asset.agents.bower:
        class: Erfans\AssetBundle\Agents\Bower\BowerAgent
        arguments:
          - "%kernel.root_dir%"
          - "@erfans_asset.util.file_system"
        tags:
          - {name: erfans_asset.agent, alias: bower}

    erfans_asset.agents.file:
        class: Erfans\AssetBundle\Agents\File\FileAgent
        arguments:
          - "@erfans_asset.util.file_system"
        tags:
          - {name: erfans_asset.agent, alias: file}

    erfans_asset.util.file_system:
        class: Erfans\AssetBundle\Util\FileSystem
        public: true
        arguments:
            - "@parameter_bag"

    # commands
    erfans_asset.commands.install:
        class: Erfans\AssetBundle\Command\InstallCommand
        arguments:
            - "@erfans_asset.asset_manager"
        tags:
            - {name: console.command}
